//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EDMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBModelEntities : DbContext
    {
        public DBModelEntities(string connstring)
            : base(connstring)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<LG_SYS_BRANCH_HOME_BANK> LG_SYS_BRANCH_HOME_BANK { get; set; }
        public DbSet<LG_USER_AREA> LG_USER_AREA { get; set; }
        public DbSet<LG_USER_CLASSIFACTION> LG_USER_CLASSIFACTION { get; set; }
        public DbSet<LG_AA_NFT_AUTH_LOG_DTLS> LG_AA_NFT_AUTH_LOG_DTLS { get; set; }
        public DbSet<LG_USER_PASS_HISTORY> LG_USER_PASS_HISTORY { get; set; }
        public DbSet<LG_FNR_ROLE> LG_FNR_ROLE { get; set; }
        public DbSet<LG_FNR_ROLE_PERMISSION> LG_FNR_ROLE_PERMISSION { get; set; }
        public DbSet<LG_FNR_ROLE_PERMISSION_DETAILS> LG_FNR_ROLE_PERMISSION_DETAILS { get; set; }
        public DbSet<LG_SYS_FAILED_LOGIN_ATTEMPT> LG_SYS_FAILED_LOGIN_ATTEMPT { get; set; }
        public DbSet<LG_FNR_ROLE_DEFINE> LG_FNR_ROLE_DEFINE { get; set; }
        public DbSet<LG_USER_ROLE_ASSIGN> LG_USER_ROLE_ASSIGN { get; set; }
        public DbSet<LG_2FA_OTP_CONFIG> LG_2FA_OTP_CONFIG { get; set; }
        public DbSet<LG_2FA_TOKEN_GEN_LOG> LG_2FA_TOKEN_GEN_LOG { get; set; }
        public DbSet<LG_CRD_PASSWORD_POLICY> LG_CRD_PASSWORD_POLICY { get; set; }
        public DbSet<LG_SYS_MAIL_SERVER_CONFIG> LG_SYS_MAIL_SERVER_CONFIG { get; set; }
        public DbSet<LG_USER_INFO> LG_USER_INFO { get; set; }
        public DbSet<LG_AA_NFT_AUTH_LOG_VAL> LG_AA_NFT_AUTH_LOG_VAL { get; set; }
        public DbSet<LG_CRD_ADC_SMS_MSG> LG_CRD_ADC_SMS_MSG { get; set; }
        public DbSet<LG_AA_NFT_AUTH_LOG> LG_AA_NFT_AUTH_LOG { get; set; }
        public DbSet<LG_AA_AUTHENTICATION_TYPE> LG_AA_AUTHENTICATION_TYPE { get; set; }
        public DbSet<LG_2FA_OTP_SMS_MSG> LG_2FA_OTP_SMS_MSG { get; set; }
        public DbSet<LG_USER_FILE_TYPE> LG_USER_FILE_TYPE { get; set; }
        public DbSet<LG_ERROR_LOG> LG_ERROR_LOG { get; set; }
        public DbSet<LG_SYS_CLD_TYPE> LG_SYS_CLD_TYPE { get; set; }
        public DbSet<LG_SYS_CLD_HOLIDAY_TYPE> LG_SYS_CLD_HOLIDAY_TYPE { get; set; }
        public DbSet<LG_SYS_HOLIDAY_MARKING> LG_SYS_HOLIDAY_MARKING { get; set; }
        public DbSet<LG_USER_CLASS_AREA_FUNCTION> LG_USER_CLASS_AREA_FUNCTION { get; set; }
        public DbSet<LG_FNR_FUNCTION_GROUP> LG_FNR_FUNCTION_GROUP { get; set; }
        public DbSet<LG_USER_AD_BINDING> LG_USER_AD_BINDING { get; set; }
        public DbSet<LG_SYS_SESSION_TRACKER> LG_SYS_SESSION_TRACKER { get; set; }
        public DbSet<LG_FNR_APPLICATION_TYPE> LG_FNR_APPLICATION_TYPE { get; set; }
        public DbSet<LG_FNR_APPLICATION> LG_FNR_APPLICATION { get; set; }
        public DbSet<LG_FNR_SERVICE> LG_FNR_SERVICE { get; set; }
        public DbSet<LG_FNR_MODULE> LG_FNR_MODULE { get; set; }
        public DbSet<LG_FNR_FUNCTION> LG_FNR_FUNCTION { get; set; }
        public DbSet<LG_USER_FILES> LG_USER_FILES { get; set; }
        public DbSet<LG_MENU_TEMP> LG_MENU_TEMP { get; set; }
        public DbSet<LG_MENU> LG_MENU { get; set; }
        public DbSet<LG_USER_ACTIVITY_LOG> LG_USER_ACTIVITY_LOG { get; set; }
        public DbSet<LG_USER_SETUP_PROFILE> LG_USER_SETUP_PROFILE { get; set; }
    }
}
