//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_2FA_TOKEN_GEN_LOG
    {
        public string USER_ID { get; set; }
        public string SESSION_ID { get; set; }
        public string TERMINAL_IP { get; set; }
        public short FUNCTION_TYPE { get; set; }
        public string FROM_BRANCH { get; set; }
        public string FROM_AC_NO { get; set; }
        public string TO_BRANCH { get; set; }
        public string TO_AC_NO { get; set; }
        public string BILL_ID_NO { get; set; }
        public Nullable<decimal> TRANS_AMOUNT { get; set; }
        public string PN { get; set; }
        public short ACTIVE_FLAG { get; set; }
        public System.DateTime GEN_TIME { get; set; }
        public Nullable<short> VERI_FLAG { get; set; }
        public Nullable<System.DateTime> VERI_TIME { get; set; }
        public Nullable<short> VERI_RESULT { get; set; }
        public Nullable<short> FAIL_REASON_ID { get; set; }
        public string CELL_NO { get; set; }
        public string SEC_CELL_NO { get; set; }
        public string PNE { get; set; }
        public string PN_TEST { get; set; }
        public string APPLICATION_ID { get; set; }
        public string CARD_NO { get; set; }
    
        public virtual LG_FNR_APPLICATION LG_FNR_APPLICATION { get; set; }
    }
}
