//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_2FA_OTP_CONFIG
    {
        public string APPLICATION_ID { get; set; }
        public short MAIL_FLAG { get; set; }
        public short SMS_FLAG { get; set; }
        public string VALIDITY_PERIOD { get; set; }
        public string NO_OF_OTP_DIGIT { get; set; }
        public string OTP_FORMAT_ID { get; set; }
        public string OTP_ID { get; set; }
        public string AUTH_STATUS_ID { get; set; }
        public string LAST_ACTION { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DT { get; set; }
        public System.DateTime MAKE_DT { get; set; }
    
        public virtual LG_FNR_APPLICATION LG_FNR_APPLICATION { get; set; }
    }
}
