//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_AA_NFT_AUTH_LOG
    {
        public LG_AA_NFT_AUTH_LOG()
        {
            this.LG_AA_NFT_AUTH_LOG_DTLS = new HashSet<LG_AA_NFT_AUTH_LOG_DTLS>();
            this.LG_AA_NFT_AUTH_LOG_VAL = new HashSet<LG_AA_NFT_AUTH_LOG_VAL>();
        }
    
        public long LOG_ID { get; set; }
        public string FUNCTION_ID { get; set; }
        public string TABLE_NAME { get; set; }
        public string TABLE_PK_COL_NM { get; set; }
        public string TABLE_PK_COL_VAL { get; set; }
        public string ACTION_STATUS { get; set; }
        public string REMARKS { get; set; }
        public short PRIMARY_TABLE_FLAG { get; set; }
        public Nullable<long> PARENT_TABLE_PK_VAL { get; set; }
        public string AUTH_STATUS_ID { get; set; }
        public short AUTH_LEVEL_MAX { get; set; }
        public short AUTH_LEVEL_PENDING { get; set; }
        public string REASON_DECLINE { get; set; }
        public string MAKE_BY { get; set; }
        public System.DateTime MAKE_DT { get; set; }
    
        public virtual ICollection<LG_AA_NFT_AUTH_LOG_DTLS> LG_AA_NFT_AUTH_LOG_DTLS { get; set; }
        public virtual ICollection<LG_AA_NFT_AUTH_LOG_VAL> LG_AA_NFT_AUTH_LOG_VAL { get; set; }
    }
}
