//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_CRD_PASSWORD_POLICY
    {
        public string SL_NO { get; set; }
        public string PASS_MAX_LENGTH { get; set; }
        public string PASS_MIN_LENGTH { get; set; }
        public short NUMERIC_CHAR_MIN { get; set; }
        public string PASS_HIS_PERIOD { get; set; }
        public short PASS_REUSE_MAX { get; set; }
        public short FAILED_LOGIN_ATTEMT { get; set; }
        public short PASS_EXP_PERIOD { get; set; }
        public short PASS_EXP_ALERT { get; set; }
        public short MIN_CAPS_LETTER { get; set; }
        public short MIN_SMALL_LETTER { get; set; }
        public short MIN_NUMERIC_CHAR { get; set; }
        public string MIN_CONS_USE_PASS { get; set; }
        public string PASS_REPEAT { get; set; }
        public short PASS_CHANGED_EXPIRY { get; set; }
        public short PASS_AUTO_CREATION { get; set; }
        public short PASS_CHANGE_BY_ADMIN { get; set; }
        public short PASS_CHANGE_AT_FIRST_LOGIN { get; set; }
        public string AUTH_STATUS_ID { get; set; }
        public string LAST_ACTION { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DT { get; set; }
        public System.DateTime MAKE_DT { get; set; }
        public string APPLICATION_ID { get; set; }
    }
}
