//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_ERROR_LOG
    {
        public short SL { get; set; }
        public string FUNCTION_ID { get; set; }
        public string ERR_SOURCE { get; set; }
        public string ERR_APP_TYPE { get; set; }
        public string ERR_METHOD { get; set; }
        public string ERR_CODE { get; set; }
        public string MESSEGE { get; set; }
        public string PREVIEW_MESSEGE { get; set; }
        public string STACK_TRACE { get; set; }
        public string MAKE_BY { get; set; }
        public Nullable<System.DateTime> MAKE_DT { get; set; }
    }
}
