//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_FNR_ROLE_DEFINE
    {
        public int SL_NO { get; set; }
        public string ROLE_ID { get; set; }
        public string FUNCTION_ID { get; set; }
        public short MAINT_CRT_FLAG { get; set; }
        public short MAINT_EDT_FLAG { get; set; }
        public short MAINT_DEL_FLAG { get; set; }
        public short MAINT_DTL_FLAG { get; set; }
        public short MAINT_INDX_FLAG { get; set; }
        public Nullable<short> MAINT_AUTH_FLAG { get; set; }
        public Nullable<short> MAINT_OTP_FLAG { get; set; }
        public Nullable<short> MAINT_2FA_FLAG { get; set; }
        public Nullable<short> MAINT_2FA_HARD_FLAG { get; set; }
        public Nullable<short> MAINT_2FA_SOFT_FLAG { get; set; }
        public short REPORT_VIEW_FLAG { get; set; }
        public short REPORT_PRINT_FLAG { get; set; }
        public short REPORT_GEN_FLAG { get; set; }
        public Nullable<short> AUTH_LEVEL { get; set; }
        public string AUTH_STATUS_ID { get; set; }
        public string LAST_ACTION { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DT { get; set; }
        public System.DateTime MAKE_DT { get; set; }
        public Nullable<short> ROLE_DEFINE_FLAG { get; set; }
        public string APPLICATION_ID { get; set; }
    
        public virtual LG_FNR_ROLE LG_FNR_ROLE { get; set; }
        public virtual LG_FNR_FUNCTION LG_FNR_FUNCTION { get; set; }
    }
}
