//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_FNR_FUNCTION
    {
        public LG_FNR_FUNCTION()
        {
            this.LG_FNR_ROLE_DEFINE = new HashSet<LG_FNR_ROLE_DEFINE>();
            this.LG_FNR_ROLE_PERMISSION_DETAILS = new HashSet<LG_FNR_ROLE_PERMISSION_DETAILS>();
            this.LG_USER_CLASS_AREA_FUNCTION = new HashSet<LG_USER_CLASS_AREA_FUNCTION>();
            this.LG_FNR_FUNCTION_GROUP = new HashSet<LG_FNR_FUNCTION_GROUP>();
        }
    
        public string FUNCTION_ID { get; set; }
        public string FUNCTION_NM { get; set; }
        public string SERVICE_ID { get; set; }
        public string MODULE_ID { get; set; }
        public string APPLICATION_ID { get; set; }
        public short MAINT_CRT_FLAG { get; set; }
        public short MAINT_EDT_FLAG { get; set; }
        public short MAINT_DEL_FLAG { get; set; }
        public short MAINT_DTL_FLAG { get; set; }
        public short MAINT_INDX_FLAG { get; set; }
        public Nullable<short> MAINT_AUTH_FLAG { get; set; }
        public short MAINT_OTP_FLAG { get; set; }
        public short MAINT_2FA_FLAG { get; set; }
        public short MAINT_2FA_HARD_FLAG { get; set; }
        public short MAINT_2FA_SOFT_FLAG { get; set; }
        public short REPORT_VIEW_FLAG { get; set; }
        public short REPORT_PRINT_FLAG { get; set; }
        public short REPORT_GEN_FLAG { get; set; }
        public string ITEM_TYPE { get; set; }
        public Nullable<short> AUTH_LEVEL { get; set; }
        public string AUTH_STATUS_ID { get; set; }
        public string LAST_ACTION { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DT { get; set; }
        public System.DateTime MAKE_DT { get; set; }
        public Nullable<short> MAINT_BIO_FLAG { get; set; }
        public Nullable<short> PROCESS_FLAG { get; set; }
        public Nullable<short> HO_FUNCTION_FLAG { get; set; }
        public string FAST_PATH_NO { get; set; }
        public string TARGET_PATH { get; set; }
        public string DB_ROLE_NAME { get; set; }
        public string FUNCTION_GROUP_ID { get; set; }
        public Nullable<short> ENABLED_FLAG { get; set; }
    
        public virtual ICollection<LG_FNR_ROLE_DEFINE> LG_FNR_ROLE_DEFINE { get; set; }
        public virtual ICollection<LG_FNR_ROLE_PERMISSION_DETAILS> LG_FNR_ROLE_PERMISSION_DETAILS { get; set; }
        public virtual ICollection<LG_USER_CLASS_AREA_FUNCTION> LG_USER_CLASS_AREA_FUNCTION { get; set; }
        public virtual ICollection<LG_FNR_FUNCTION_GROUP> LG_FNR_FUNCTION_GROUP { get; set; }
    }
}
