//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_FNR_ROLE
    {
        public LG_FNR_ROLE()
        {
            this.LG_FNR_ROLE_DEFINE = new HashSet<LG_FNR_ROLE_DEFINE>();
        }
    
        public string ROLE_ID { get; set; }
        public string ROLE_NAME { get; set; }
        public string ROLE_DESCRIP { get; set; }
        public short IS_SYS_ADMIN { get; set; }
        public string AUTH_STATUS_ID { get; set; }
        public string LAST_ACTION { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DT { get; set; }
        public System.DateTime MAKE_DT { get; set; }
    
        public virtual ICollection<LG_FNR_ROLE_DEFINE> LG_FNR_ROLE_DEFINE { get; set; }
    }
}
