//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_MENU
    {
        public decimal SL_ID { get; set; }
        public string APP_ID { get; set; }
        public Nullable<decimal> MENU_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string CONTROLLER { get; set; }
        public string ACTION { get; set; }
        public string URL { get; set; }
        public Nullable<decimal> PARENTID { get; set; }
        public string FUNCTION_ID { get; set; }
        public Nullable<short> MENU_LEVEL { get; set; }
        public Nullable<short> FUNCTION_ASSIGN_FLAG { get; set; }
        public Nullable<short> MENU_ENABLE_FLAG { get; set; }
    }
}
