//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_MENU_TEMP
    {
        public decimal MENU_ID { get; set; }
        public string ITEM_TYPE { get; set; }
        public string MENU_NM { get; set; }
        public Nullable<int> MENU_LEVEL { get; set; }
        public Nullable<decimal> PARENT_MENU_ID { get; set; }
        public Nullable<short> FUNCTION_ASSIGN_FLAG { get; set; }
        public string FIRST_PATH_NO { get; set; }
        public string FUNCTION_ID { get; set; }
        public string FUNCTION_NM { get; set; }
        public Nullable<short> HO_FUNCTION_FLAG { get; set; }
        public string TARGET_PATH { get; set; }
        public string DB_ROLE_NAME { get; set; }
        public string SERVICE_ID { get; set; }
        public string MODULE_ID { get; set; }
        public Nullable<short> ALLOW_MAINT_ADD_FLAG { get; set; }
        public Nullable<short> ALLOW_MAINT_EDIT_FLAG { get; set; }
        public Nullable<short> ALLOW_MAINT_DEL_FLAG { get; set; }
        public Nullable<short> ALLOW_MAINT_VIEW_FLAG { get; set; }
        public Nullable<short> ALLOW_MAINT_AUTH_FLAG { get; set; }
        public Nullable<short> ALLOW_PROCESS_FLAG { get; set; }
        public Nullable<short> ALLOW_REPORT_VIEW_FLAG { get; set; }
        public Nullable<short> ALLOW_REPORT_PRINT_FLAG { get; set; }
        public Nullable<short> ALLOW_REPORT_GEN_FLAG { get; set; }
        public string HELP_PATH { get; set; }
    }
}
