//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_SYS_CLD_TYPE
    {
        public LG_SYS_CLD_TYPE()
        {
            this.LG_SYS_HOLIDAY_MARKING = new HashSet<LG_SYS_HOLIDAY_MARKING>();
        }
    
        public short CLD_TYPE_ID { get; set; }
        public string CLD_TYPE_NM { get; set; }
        public short DEFAULT_CLD { get; set; }
        public string BASED_ON_CLD { get; set; }
        public string MAKE_BY { get; set; }
        public Nullable<System.DateTime> MAKE_DT { get; set; }
        public string AUTH_STATUS_ID { get; set; }
        public string LAST_ACTION { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DT { get; set; }
    
        public virtual ICollection<LG_SYS_HOLIDAY_MARKING> LG_SYS_HOLIDAY_MARKING { get; set; }
    }
}
