//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_SYS_SESSION_TRACKER
    {
        public string SL_NO { get; set; }
        public string USER_ID { get; set; }
        public string SESSION_ID { get; set; }
        public System.DateTime START_TIME { get; set; }
        public System.DateTime LAST_ACCESS_TIME { get; set; }
        public string IP_ADDRESS { get; set; }
        public short ACTIVE_FLAG_FOR_MULTI_LOGIN { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> SESSION_DT { get; set; }
        public string APPLICATION_ID { get; set; }
    }
}
