//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_USER_CLASSIFACTION
    {
        public LG_USER_CLASSIFACTION()
        {
            this.LG_USER_AREA = new HashSet<LG_USER_AREA>();
            this.LG_USER_CLASS_AREA_FUNCTION = new HashSet<LG_USER_CLASS_AREA_FUNCTION>();
            this.LG_USER_SETUP_PROFILE = new HashSet<LG_USER_SETUP_PROFILE>();
        }
    
        public string CLASSIFICATION_ID { get; set; }
        public string CLASSIFICATION_NAME { get; set; }
        public string AUTH_STATUS_ID { get; set; }
        public string LAST_ACTION { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DT { get; set; }
        public System.DateTime MAKE_DT { get; set; }
    
        public virtual ICollection<LG_USER_AREA> LG_USER_AREA { get; set; }
        public virtual ICollection<LG_USER_CLASS_AREA_FUNCTION> LG_USER_CLASS_AREA_FUNCTION { get; set; }
        public virtual ICollection<LG_USER_SETUP_PROFILE> LG_USER_SETUP_PROFILE { get; set; }
    }
}
