//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_USER_AD_BINDING
    {
        public int SL { get; set; }
        public string USER_ID { get; set; }
        public string DOMAIN_ID { get; set; }
        public string DOMAIN { get; set; }
        public short AD_ACTIVE_FLAG { get; set; }
        public string AUTH_STATUS_ID { get; set; }
        public string LAST_ACTION { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DT { get; set; }
        public Nullable<System.DateTime> MAKE_DT { get; set; }
    }
}
