//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_USER_SETUP_PROFILE
    {
        public decimal SL_ID { get; set; }
        public string USER_ID { get; set; }
        public string USER_CLASSIFICATION_ID { get; set; }
        public string USER_AREA_ID { get; set; }
        public string USER_AREA_ID_VALUE { get; set; }
        public string USER_NM { get; set; }
        public string USER_DESCRIP { get; set; }
        public string BRANCH_ID { get; set; }
        public string ACC_NO { get; set; }
        public string FATHERS_NM { get; set; }
        public string MOTHERS_NM { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string MAIL_ADDRESS { get; set; }
        public string MOB_NO { get; set; }
        public string AUTHENTICATION_ID { get; set; }
        public string TERMINAL_IP { get; set; }
        public Nullable<short> WORKING_HOUR { get; set; }
        public string START_TIME { get; set; }
        public string END_TIME { get; set; }
        public string PASSWORD { get; set; }
        public string AUTH_STATUS_ID { get; set; }
        public string LAST_ACTION { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DT { get; set; }
        public Nullable<System.DateTime> MAKE_DT { get; set; }
        public string MAKE_BY { get; set; }
        public short USER_ID_LOCK_WRNG_ATM { get; set; }
        public short ACTIVE_FLAG_INACTV_USER { get; set; }
        public short ACTIVE_FLAG_MULTI_LOGIN { get; set; }
        public string FAILED_LOGIN_ATTEMPT { get; set; }
        public short FIRST_LOGIN_FLAG { get; set; }
    
        public virtual LG_AA_AUTHENTICATION_TYPE LG_AA_AUTHENTICATION_TYPE { get; set; }
        public virtual LG_SYS_BRANCH_HOME_BANK LG_SYS_BRANCH_HOME_BANK { get; set; }
        public virtual LG_USER_AREA LG_USER_AREA { get; set; }
        public virtual LG_USER_CLASSIFACTION LG_USER_CLASSIFACTION { get; set; }
    }
}
