//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_USER_PASS_HISTORY
    {
        public string SL_NO { get; set; }
        public string USER_ID { get; set; }
        public string PASSWORD_STRING { get; set; }
        public string APPLICATION_ID { get; set; }
        public string APPLICATION_NAME { get; set; }
        public System.DateTime MAKE_DT { get; set; }
        public string AUTH_STATUS_ID { get; set; }
        public string MAKE_BY { get; set; }
        public string LAST_ACTION { get; set; }
        public string LAST_UPDATE_DT { get; set; }
    }
}
