//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_USER_ACTIVITY_LOG
    {
        public int SL_ID { get; set; }
        public string USER_ID { get; set; }
        public string ACCOUNT_NO { get; set; }
        public string BRANCH_ID { get; set; }
        public System.DateTime DATE_TIME { get; set; }
        public string ACTION { get; set; }
        public string PARAMETERS { get; set; }
        public string CURRENT_PAGE { get; set; }
        public string IP_ADDRESS { get; set; }
    }
}
