//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_USER_INFO
    {
        public string USER_ID { get; set; }
        public string CUST_ID { get; set; }
        public string GROUP_ID { get; set; }
        public string CELL_NO { get; set; }
        public string EMAIL_ID { get; set; }
        public System.DateTime REG_DT { get; set; }
        public decimal ACTIVE_FLAG { get; set; }
        public string SEC_CELL_NO { get; set; }
        public string APPLICATION_ID { get; set; }
    }
}
